name: Update Cloudflare Usage

on:
  schedule:
    - cron: '0 */1 * * *' # هر 1 ساعت یکبار اجرا می‌شود
  workflow_dispatch: # امکان اجرای دستی را هم فراهم می‌کند

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-node-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        CF_API_TOKEN: ${{ secrets::CF_API_TOKEN }}
        CF_ACCOUNT_ID: ${{ secrets::CF_ACCOUNT_ID }}
      run: python update_usage.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Cloudflare usage stats [skip ci]"
        git push
